version: '3.8'

services:
  localcontextmcp:
    build: .
    ports:
      - "8080:8080"
    environment:
      - PGHOST=db
      - PGPORT=5432
      - PGDATABASE=mcp_memory
      - PGUSER=postgres
      - PGPASSWORD=postgres
      - LMSTUDIO_API_BASE=http://lms:1234/v1
      - LMSTUDIO_EMBEDDING_MODEL=qwen2.5-coder-0.5B-instruct
      - SMITHERY_API_KEY=${SMITHERY_API_KEY}
      - DOCKER_CONTAINER=true
    depends_on:
      - db
      - lms
    networks:
      - mcp-network
    restart: unless-stopped
    volumes:
      - /Users/m3/AI/LocalContextMCP:/projects/bot-env
    stdin_open: true
    tty: true

  db:
    image: postgres:15
    environment:
      - POSTGRES_DB=mcp_memory
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mcp-network
    restart: unless-stopped

  lms:
    image: node:20-alpine # Placeholder, replace with actual LM Studio image if available
    command: ["sh", "-c", "npx -y lms server start --host 0.0.0.0 --port 1234"]
    ports:
      - "1234:1234"
    networks:
      - mcp-network
    restart: unless-stopped

volumes:
  postgres_data:

networks:
  mcp-network:
    driver: bridge 